import { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: '7',
    slug: 'proposeflow',
    title: 'ProposeFlow',
    description: 'An AI-powered object generation service that treats LLM output as proposals requiring human approval before reaching your database. Users describe what they need in natural language, review the structured result, and approve, edit, or reject with feedback — closing the gap between LLM capability and production data quality.',
    technologies: ['Next.js', 'TypeScript', 'Fastify', 'PostgreSQL', 'Prisma', 'AWS', 'Tailwind CSS'],
    liveUrl: 'https://proposeflow.ai',
    liveUrlText: 'Visit Site',
    imageUrl: 'https://placehold.co/600x400/6366f1/ffffff?text=ProposeFlow',
    featured: true,
    story: 'LLMs are powerful but imperfect — they hallucinate, miss context, and make mistakes. I built ProposeFlow to solve this by adding a human checkpoint between AI generation and your database. Developers define a schema, users type plain English, and the system proposes a structured object for review. If rejected, AI regenerates based on the feedback. The result is AI-generated content that users can actually trust.',
  },
  {
    id: '8',
    slug: 'habitu',
    title: 'Habitu',
    description: 'A multi-platform AI-powered productivity app that turns goals into actionable schedules. Describe your goals in plain English and the AI generates tasks, proposes smart schedules, and tracks your progress with streaks and achievements — available on web, iOS, and desktop.',
    technologies: ['Next.js', 'React Native', 'Tauri', 'TypeScript', 'Convex', 'AWS Bedrock', 'Tailwind CSS'],
    liveUrl: 'https://habitu.ai',
    liveUrlText: 'Visit Site',
    imageUrl: 'https://placehold.co/600x400/10b981/ffffff?text=Habitu',
    featured: true,
    story: 'I wanted a productivity tool that actually understood my schedule instead of just being another to-do list. Habitu uses AI to break down goals into recurring and one-time tasks, then intelligently suggests when to work on them based on your calendar and habits. The hardest part was building a shared codebase across web, mobile, and desktop — a monorepo with shared types and business logic made that possible.',
  },
  {
    id: '9',
    slug: 'amazon-brand-stores',
    title: 'Amazon Brand Stores',
    description: 'A self-service storefront builder that lets brands create dedicated, multi-page shopping experiences on Amazon. Features a drag-and-drop editor, customizable templates, product catalogs, lifestyle imagery, video content, and Store Insights analytics — serving millions of shoppers worldwide.',
    technologies: ['React', 'TypeScript', 'Java', 'AWS'],
    liveUrl: 'https://advertising.amazon.com/solutions/products/stores',
    liveUrlText: 'Learn More',
    imageUrl: 'https://placehold.co/600x400/ff9900/ffffff?text=Amazon+Brand+Stores',
    featured: true,
    story: 'I\'ve been on the Brand Stores team in Amazon Advertising since 2019, helping build the storefront experience that brands use to showcase their products and tell their story on Amazon. The platform drives real impact — new-to-brand shoppers who visit a Brand Store are 62.7% more likely to purchase and spend 72.3% more on average.',
  },
  {
    id: '10',
    slug: 'exiled',
    title: 'Exiled',
    description: 'A browser-based city-building survival game inspired by Banished, Stardew Valley, and Cities: Skylines. Guide a group of exiled travelers as they build a new settlement, manage resources, and survive harsh seasons — all rendered on HTML5 Canvas with zero external dependencies.',
    technologies: ['TypeScript', 'Vite', 'HTML5 Canvas', 'ECS Architecture'],
    liveUrl: 'https://quinton.dev/exiled-game/',
    liveUrlText: 'Play Game',
    imageUrl: 'https://placehold.co/600x400/b45309/ffffff?text=Exiled',
    featured: true,
    story: 'I wanted to see how far I could push a pure TypeScript + Canvas game with no engine or framework. Exiled features deep citizen AI with personality traits and skill progression, 27 building types, a 12-sub-season cycle, cooking and livestock systems, festivals, disease, weather events, and a tightly tuned resource economy designed to keep players on the edge of the "death spiral" without falling in. Every system — from A* pathfinding to the ECS architecture — was built from scratch.',
  },
];
